version: '3.9'

services:
  backend:
    build: .
    ports:
      - '5104:5104'
      - '11434:11434'
    environment:
      - OLLAMA_URL=http://localhost:11434
    volumes:
      - ollama_data:/root/.ollama

volumes:
  ollama_data:
